<?php

/**
 * @file
 * News Categories vocabulary installation file.
 */

use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_install().
 */
function utnews_vocabulary_categories_install() {
  $profile_groups = ['General', 'Opinion', 'Press Releases'];
  $weight = 0;
  foreach ($profile_groups as $term) {
    Term::create([
      'name' => $term,
      'vid' => 'utnews_categories',
      'weight' => $weight,
    ])->save();
    $weight++;
  }
}
