<?php

/**
 * @file
 * Contains utnews content type .module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

use Drupal\utnews_content_type_news\NewsContentTypeHelper;

/**
 * Implements hook_theme().
 */
function utnews_content_type_news_theme() {
  return [
    'node__utnews_news__full' => [
      'template' => 'node--utnews-news--full',
      'base hook' => 'node',
    ],
    'node__utnews_news__teaser' => [
      'template' => 'node--utnews-news--teaser',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function utnews_content_type_news_preprocess_node(&$variables) {
  $node = $variables['elements']['#node'];
  $type = $node->getType();
  $view_mode = $variables['view_mode'];

  if ($type !== 'utnews_news') {
    return;
  }

  $variables['has_sidebar_fields'] = NewsContentTypeHelper::hasSidebarFields($node);
  $variables['author_information'] = NewsContentTypeHelper::prepareAuthorInformation($node);
  $variables['main_image'] = NewsContentTypeHelper::prepareMainImage($node);
  $variables['news_tags'] = NewsContentTypeHelper::prepareNewsTaxonomy($node, 'field_utnews_news_tags', 'tags');
  $variables['news_categories'] = NewsContentTypeHelper::prepareNewsTaxonomy($node, 'field_utnews_news_categories', 'categories');
  $variables['linked_title'] = NewsContentTypeHelper::prepareLinkedTitle($node);
  $variables['body_summary'] = $node->get('field_utnews_body')->getValue()[0]['summary'];

  // The Views field handler `NewsListing` can be applied to all view modes and
  // allows for optionally suppressing 3 fields, listed below, based on
  // the settings values indicated.
  $dynamic_display = [
    '#display_date' => 'field_utnews_publication_date',
    '#display_summary' => 'field_utnews_body',
    '#display_thumbnail' => 'field_utnews_main_media',
  ];
  foreach ($dynamic_display as $setting => $field) {
    if (isset($variables['elements'][$setting]) && $variables['elements'][$setting] === FALSE) {
      unset($variables['content'][$field]);
    }
  }

  switch ($view_mode) {
    case 'full':
      $variables['#attached']['library'][] = 'utnews_content_type_news/node-display';
      break;

    case 'teaser':
      $variables['#attached']['library'][] = 'utnews_content_type_news/view-mode-teaser';
      break;
  }
}

/**
 * Implements hook_node_view_alter().
 */
function utnews_content_type_news_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Bypass render cache for News teasers, since we build their content
  // dynamically. See utnews/issues/230.
  if ($entity->bundle() == 'utnews_news' && $build['#view_mode'] == 'teaser') {
    $build['#cache']['max-age'] = 0;
  }
}
