<?php

/**
 * @file
 * Module file for UTNews listing page.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\utnews_view_listing_page\Form\ListingPageConfig;
use Drupal\views\ViewExecutable;
use Drupal\utnews_content_type_news\NewsContentTypeHelper;

/**
 * Implements hook_theme().
 */
function utnews_view_listing_page_theme() {
  // Provide News listing-specific page template.
  $theme['page__news'] = [
    'template' => 'page--news',
    'base hook' => 'page',
  ];

  return $theme;
}

/**
 * Implements hook_form_FORM_ID_alter() for the general config form.
 */
function utnews_view_listing_page_form_utnews_general_config_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Alter the general config form to include an the listing page title.
  \Drupal::classResolver(ListingPageConfig::class)->alterForm($form, $form_state, $form_id);
}

/**
 * Implements hook_views_post_render().
 */
function utnews_view_listing_page_views_post_render(ViewExecutable $view) {
  // Set the page title based on editor-provided value.
  $view_id = 'utnews_listing_page';
  if ($view->id() !== $view_id) {
    return;
  }
  $config = \Drupal::config('utnews_view_listing_page.config');
  if ($title = $config->get('page_title')) {
    // Set the view title.
    $view->setTitle($title);
    // Set the route title.
    $route = \Drupal::routeMatch()->getCurrentRouteMatch()->getRouteObject();
    $route->setDefault('_title', $title);
  }
}

/**
 * Implements hook_views_pre_render().
 */
function utnews_view_listing_page_views_pre_render(ViewExecutable $view) {
  $view_id = 'utnews_listing_page';
  if ($view->storage->id() === $view_id) {
    $view->element['#attached']['library'][] = 'utnews_view_listing_page/utnews-listing-page';
    $view->element['#attached']['library'][] = 'utexas_layout_builder_styles/border-styles';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function utnews_view_listing_page_preprocess_page__news(&$variables) {
  // Styling variables.
  $variables['attributes']['class'][] = 'utexas-field-border';
  $variables['attributes']['class'][] = 'utexas-field-background';
  $variables['#attached']['library'][] = 'utnews_view_listing_page/facet-display';
}

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
function utnews_view_listing_page_plugin_filter_block__layout_builder_alter(array &$definitions) {
  // News facets are not designed to be placed with Layout Builder.
  // Suppress them from that context.
  unset($definitions['facet_block:author']);
  unset($definitions['facet_block:categories']);
  unset($definitions['facet_block:tags']);
  unset($definitions['facets_summary_block:utnews']);
}
