<?php

/**
 * @file
 * Utnews overrides.
 */

use Drupal\Core\Form\FormStateInterface;

use Drupal\utprof_overrides\Form\FieldFormAlterations;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function utnews_overrides_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Modify field forms using Drupal\utnews_overrides\Form.
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(FieldFormAlterations::class)
    ->fieldConfigEditFormAlter($form, $form_state, $form_id);
}
