name: Check syntax of changed files in a pull request

on:
  # Triggers the workflow when a new commit is pushed to the HEAD ref of a pull request
  pull_request:
    types: [opened, reopened, synchronize]
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checksyntax:
    runs-on: [ wcs-gh-t01 ]
    steps:
      - uses: actions/checkout@v3
      - name: CHECK SYNTAX
        uses: eis1-wcs/utdk3-build-action@main
        env:
          BRANCH: ${{github.event.pull_request.head.ref}}
          ENTRYPOINT: .github/workflows/scripts/check_syntax.sh
